# Indexing or Slicing in Array
arr[dimension, row, column]

Each of them can be sliced as with as [start:stop:step]


In [2]:
import numpy as np

In [6]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
print("Shape: ",a.shape)
print("Number of dimensions: ",a.ndim)
print("Shape: ", a.shape)

Shape:  (2, 5)
Number of dimensions:  2
Shape:  (2, 5)


# Indexing 2 Dimensional array


In [21]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [54]:
#Indexing a specific element
print(a[0,0])   #0th column of 0th row
print(a[1,2])   #1th column of 1th row
print(a[-1,-1])  #Last column of last row

90
8
10


In [23]:
#Slice a specific row
a[0, :]  #returns all the columns of the row at 0th index

array([1, 2, 3, 4, 5])

In [25]:
#Slice a specific column
a[:,0] #returns all the row items of the column at 0 the index

array([1, 6])

In [28]:
#Slicing range of items from a specific row
a[0, 2:4]  # returns the element at 2:4 index of the row at 0th index

array([3, 4])

In [30]:
#Slicing range of items from a specific column
a[0:2, 0] #returns the items at 0 and 1 index of the column at 0th index

array([1, 6])

## Replacing the indexed item's value
 Tip for Replacing:
 First look at the sliced part and then form the array or list according to it.

In [33]:
#Replacing a single item's value
a[0,0] = 90
a

array([[90,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
#Replacing multiple item (range)'s value [with the same single value]
a[0,2:] = 5   #Replaces the value of the items at 2: index with 5
a

array([[90,  2,  5,  5,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
#Replacing multiple item's value by passing an array (i.e. with different values)
print("Initially: ",a[0,2:])
a[0,2:] = [70,56,5656]
print("\nAfter slicing and replacing:",a[0,2:], sep = '\n')

Initially:  [5 5 5]

After slicing and replacing:
[  70   56 5656]


# Indexing 3 Dimensional array

Note:
Try the outside in approach.
i.e The dimension first and then the row and finally the column (item)

In [53]:
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [57]:
#Indexing a specific item
#Let's get 4 from the array above

#It is in the oth channel's, 1th row's, 1th column

b[0,1,1]

4

In [58]:
#Indexing multiple items

In [64]:
#Indexing specific dimension/channel
print("The 0th channel: \n", b[0,:,:])
print("\nThe 1th channel: \n", b[1,:,:])

The 0th channel: 
 [[1 2]
 [3 4]]

The 1th channel: 
 [[5 6]
 [7 8]]


In [68]:
#Indexing specific row of all the channels
b[:,0,:]  #returns all the column items in 0th row of both channels

array([[1, 2],
       [5, 6]])

In [71]:
#Indexing specific column of all the rows of all the channels
b[:,:,0]  #returns all the items in the 0th column of each row of each channel

array([[1, 3],
       [5, 7]])

## Replacing the indexed items' value