In [2]:
#Creating arrays of different dimensions
import numpy as np

#One dimensional array
arr = np.array([1,2,3])
print("One dimensional array \n",arr)

#Two dimensional array
arr2 = np.array([(1,2,3),(4,5,6)])
print("\nTwo dimensional array \n", arr2)

#Another two dimensional array
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("\nAnother 2 dimensional array \n", arr1)

#Three dimensional array
arr3 = np.array([ [(1,2,3),(4,5,6)], [(1,2,3),(4,5,6)]  ])
print("\nThree dimensional array \n", arr3)

One dimensional array 
 [1 2 3]

Two dimensional array 
 [[1 2 3]
 [4 5 6]]

Another 2 dimensional array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Three dimensional array 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [3]:
#Other ways to create arrays

#Create a 3x3 array filled with 4
arr = np.full((3,3),4)  # the first argument takes the shape and the second arg takes the element to be placed
print(arr)

#Range in array
#Create an array of linear sequence starting 0 and ending at 9
arr2 = np.arange(0,10)
print("\n",arr2)

[[4 4 4]
 [4 4 4]
 [4 4 4]]

 [0 1 2 3 4 5 6 7 8 9]


In [4]:
#Creating arrays filled with ones and zeros

#Creating array filled with 0 by only specifying the columns (1 row is taken)
zer = np.zeros(5, dtype = np.int)  #1 row and 5 columns
print(zer)


#Creating array filled with 0 by specifying the rows and column num
zer = np.zeros([2,3], dtype = np.int32) #2 rows and 3 columns
print("\n", zer)

#Creating array filled with 0 specifying the dimensions along with rows and columns
zer = np.zeros([3,2,3], dtype = np.int) # 3 dimensions, 2 rows and 3 columns
print('\n', zer)

[0 0 0 0 0]

 [[0 0 0]
 [0 0 0]]

 [[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [5]:
#Creating arrays using random elements

#Creating a random array of specified shape (rows and columns) 
arr = np.random.random((3,3))
print("Random array with rows and columns specified\n",arr)

#Same as above but with dimension too
arr = np.random.random((3,3,3))
print("\nRandom array with dimensions specified\n",arr)

#Creating a random array with range specified 
arr = np.random.randint(0,10,(3,2))
print("\nRandom array with the range of intgers specified\n",arr)

Random array with rows and columns specified
 [[0.4482922  0.75833113 0.86434773]
 [0.81571033 0.4176769  0.20668751]
 [0.60634598 0.43649885 0.32961163]]

Random array with dimensions specified
 [[[0.58798158 0.09268336 0.58301115]
  [0.70716152 0.91730591 0.5206874 ]
  [0.28934438 0.38273049 0.09976189]]

 [[0.55941661 0.50537467 0.97485908]
  [0.86383363 0.51865214 0.37414784]
  [0.78156312 0.21935038 0.89161908]]

 [[0.65443372 0.58168692 0.23151495]
  [0.31093489 0.03581987 0.17816792]
  [0.4931328  0.68341285 0.75895987]]]

Random array with the range of intgers specified
 [[9 5]
 [5 9]
 [1 4]]


In [6]:
#Finding out the dimension of any array
import numpy as np

arr = np.array([1,2,3])  #only a single row
arr1 = np.array([(1,2,3),(4,5,6)])    # Two rows
arr2 = np.array([(1,2,3),(1,3,5),(3,4,5)])  #Three rows
arr3 = np.array([[(1,2,3),(4,5,6)],[(3,4,5),(3,4,5)]])  

print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
2
3


In [7]:
#Finding out the itemsize of elements in an array
arr = np.array([1,2,3])

print(arr.itemsize)


4


In [8]:
#Finding out the data type of elements in an array
arr = np.array([1,2,3])

print(arr.dtype)


int32


In [9]:
#Finding the size of the whole array (i.e.the number of elements in the array)

arr = np.array([1,2,3])
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(1,3,5),(3,4,5)])

print(arr.size)
print(arr1.size)
print(arr2.size)

3
6
9


In [10]:
#Finding the shape of an array (i.e. the number of rows and columns)

arr = np.array([1,2,3,4,5,6,7])
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(1,3,5),(3,4,5)])
arr3 = np.array([(1,2,3),(1,3,5)])

print(arr.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(7,)
(2, 3)
(3, 3)
(2, 3)


In [11]:
#Reshaping the array (Changing rows and columns)

arr = np.array([1,2,3,4,5,6,7])
print("Inital array ",arr)
arr = arr.reshape(7,1)
print("\nReshaped array ",arr)

Inital array  [1 2 3 4 5 6 7]

Reshaped array  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [12]:
#Reshaping the array (Changing rows and columns)
arr1 = np.array([(1,2,3),(4,5,6)])
print("Initial array \n", arr1)
arr1 = arr1.reshape(3,2)
print("\nReshaped array \n", arr1)

Initial array 
 [[1 2 3]
 [4 5 6]]

Reshaped array 
 [[1 2]
 [3 4]
 [5 6]]


In [13]:
#Slicing an array
arr = np.array([(1,2,3,4),(4,5,6,8)])

#Print statement to return the 3rd index value in each row
print(arr[0:, 3])

[4 8]
