In [2]:
#Finding out the dimension of any array
import numpy as np

arr = np.array([1,2,3])  #only a single row
arr1 = np.array([(1,2,3),(4,5,6)])    # Two rows
arr2 = np.array([(1,2,3),(1,3,5),(3,4,5)])  #Three rows
arr3 = np.array([[(1,2,3),(4,5,6)],[(3,4,5),(3,4,5)]])  

print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
2
3


In [3]:
#Finding out the itemsize of elements in an array
arr = np.array([1,2,3])

print(arr.itemsize)    #Shows the size of each item in bytes


4


In [4]:
#Finding out the data type of elements in an array
arr = np.array([1,2,3])

print(arr.dtype)


int32


In [10]:
#Finding the size of the whole array (i.e.the number of elements in the array)

arr = np.array([1,2,3])
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(1,3,5),(3,4,5)])

print(arr.size)
print(arr1.size)
print(arr2.size)

3
6
9


In [11]:
#Finding the total size(number of bytes occupied by the array)
#Equivalent to arr.size * arr.itemsize

arr = np.array([1,2,3])
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(1,3,5),(3,4,5)])

print(arr.nbytes)
print(arr1.nbytes)
print(arr2.nbytes)

12
24
36


In [6]:
#Finding the shape of an array (i.e. the number of rows and columns)

arr = np.array([1,2,3,4,5,6,7])
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(1,3,5),(3,4,5)])
arr3 = np.array([(1,2,3),(1,3,5)])

print(arr.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(7,)
(2, 3)
(3, 3)
(2, 3)


In [7]:
#Reshaping the array (Changing rows and columns)

arr = np.array([1,2,3,4,5,6,7])
print("Inital array ",arr)
arr = arr.reshape(7,1)
print("\nReshaped array \n",arr)

Inital array  [1 2 3 4 5 6 7]

Reshaped array 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [8]:
#Reshaping the array (Changing rows and columns)
arr1 = np.array([(1,2,3),(4,5,6)])
print("Initial array \n", arr1)
arr1 = arr1.reshape(3,2)
print("\nReshaped array \n", arr1)

Initial array 
 [[1 2 3]
 [4 5 6]]

Reshaped array 
 [[1 2]
 [3 4]
 [5 6]]


In [9]:
#Slicing an array
arr = np.array([(1,2,3,4),(4,5,6,8)])

#Print statement to return the 3rd index value in each row
print(arr[0:, 3])  #arr[<column_index>, <row_index>]

[4 8]
