In [1]:
import numpy as np


1. Creating Numpy Array

In [2]:
l = [1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

In [3]:
l = [[1,2],[3,4]]
np.array(l)

array([[1, 2],
       [3, 4]])

In [4]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [6]:
z = np.ones(5)
z

array([1., 1., 1., 1., 1.])

In [13]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [11]:
np.linspace(1,10,5) #5 evenly separated points between 1 and 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
np.random

<module 'numpy.random' from 'C:\\Users\\hp\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

While slicing an array, the sliced part is a direct image of the origina one.
so changing th 

ravel function will bring back any multidimensional array into 1 D

In [19]:
#Transposing a matric
arr = np.arange(9).reshape(3,3)
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [20]:
#Sum and average in array
arr = np.arange(9).reshape(3,3)
print(sum(arr))
print(arr.avg)

<built-in method sum of numpy.ndarray object at 0x000002315D004F30>


AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [23]:
x1 = np.random.randint(1,10,10)
m = np.mean(x1) 
dev = x1 - m
sumdev = np.sum(dev)
sq = sumdev**2
dev 

In [26]:
#Axis in sum
x1 = np.random.randint(1,10,10)


In [ ]:
#Standard Deviation
np.sqrt(np.sum(d**2)/10)
